name: Deploy Java SprintBoot Application (open-nse-price)

on:
    push: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Set up Maven - Test
              uses: s4u/setup-maven-action@v1.11.0
              with:
                maven-version: 3.8.2
                java-version: 17

            - run: mvn -V clean install

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Image and Push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/open-nse-price:${{ github.sha }}



                

        

            