name: Deploy Java SprintBoot Application (open-nse-price)

on:
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Set up Maven - Test
              uses: s4u/setup-maven-action@v1.11.0
              with:
                maven-version: 3.8.2
                java-version: 17

            - run: mvn -V clean install



                

        

            